### PR TITLE
Let `--help` show the envvars respected by CLI

### PR DESCRIPTION
**Pull request by alanjds**
This makes the envvars respected easily discoverable and directly accessible for end users.

```console
$ polyswarm --help
Usage: polyswarm [OPTIONS] COMMAND [ARGS]...

  This is a PolySwarm CLI client, which allows you to interact directly with
  the PolySwarm network to scan files, search hashes, and more.

Options:
  -a, --api-key TEXT              Your API key for polyswarm.network
                                  (required). $POLYSWARM_API_KEY
  -u, --api-uri TEXT              The API endpoint (ADVANCED).
                                  $POLYSWARM_API_URI
(...)
  -c, --community TEXT            Community to use. $POLYSWARM_COMMUNITY
(...)
```

### CODE REVIEW

**Review by mjbradford89 — APPROVED** [review]

**Comment by alanjds** [comment]
FYI: Would also be possible to have automated envvar names accepted: https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables

However idk if this is useful, as is not explicit and does not generate docs on --help

**Comment by alanjds** [comment]
> There is also an option to automate the display of the env name `show_envvar`

This is interesting. I will try and possibly send another PR

**Comment by alanjds** [comment]
The result with `show_envvar=True` is:
```
Options:
  -a, --api-key TEXT              Your API key for polyswarm.network
                                  (required).  [env var: POLYSWARM_API_KEY]
  -u, --api-uri TEXT              The API endpoint (ADVANCED).  [env var:
                                  POLYSWARM_API_URI]
(...)
  -c, --community TEXT            Community to use.  [env var:
                                  POLYSWARM_COMMUNITY]
```

I am in favor of using `show_envvar` as it is automated. Less room for future unsync.

**Comment by mrsarm** [comment]
> I am in favor of using show_envvar as it is automated.

Yes, agree.

**Pull request merged**
